# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import repo_service_pb2 as repo__service__pb2


class RepoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Save = channel.unary_unary(
        '/RepoService/Save',
        request_serializer=repo__service__pb2.User.SerializeToString,
        response_deserializer=repo__service__pb2.User.FromString,
        )
    self.FindById = channel.unary_unary(
        '/RepoService/FindById',
        request_serializer=repo__service__pb2.User_Id.SerializeToString,
        response_deserializer=repo__service__pb2.User.FromString,
        )
    self.FindByEmail = channel.unary_unary(
        '/RepoService/FindByEmail',
        request_serializer=repo__service__pb2.UserEmail.SerializeToString,
        response_deserializer=repo__service__pb2.User.FromString,
        )
    self.ResetDatabase = channel.unary_unary(
        '/RepoService/ResetDatabase',
        request_serializer=repo__service__pb2.Empty.SerializeToString,
        response_deserializer=repo__service__pb2.Empty.FromString,
        )


class RepoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Save(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindByEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResetDatabase(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RepoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Save': grpc.unary_unary_rpc_method_handler(
          servicer.Save,
          request_deserializer=repo__service__pb2.User.FromString,
          response_serializer=repo__service__pb2.User.SerializeToString,
      ),
      'FindById': grpc.unary_unary_rpc_method_handler(
          servicer.FindById,
          request_deserializer=repo__service__pb2.User_Id.FromString,
          response_serializer=repo__service__pb2.User.SerializeToString,
      ),
      'FindByEmail': grpc.unary_unary_rpc_method_handler(
          servicer.FindByEmail,
          request_deserializer=repo__service__pb2.UserEmail.FromString,
          response_serializer=repo__service__pb2.User.SerializeToString,
      ),
      'ResetDatabase': grpc.unary_unary_rpc_method_handler(
          servicer.ResetDatabase,
          request_deserializer=repo__service__pb2.Empty.FromString,
          response_serializer=repo__service__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RepoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
